---
#
# Tasks to be applied to the cluster, but not nessesarily to the master
#

- name: Setup the various k3s compontentes
  include_tasks: "{{ comp }}"
  loop_control:
    loop_var: comp
  with_fileglob:
    - components/cert-manager.yml
    - components/kuma.yml
    - components/argocd.yml
    - components/traefik-dashboard.yml
  when: ansible_host == etcd_leader_ip
