# configure global
- name: Configure the global git color usage
  community.general.git_config:
    name: color.ui
    scope: global
    value: auto
- name: Configure the global git username
  community.general.git_config:
    name: user.name
    scope: global
    value: "Frank Elsinga"
- name: Configure the global git useremail
  community.general.git_config:
    name: user.email
    scope: global
    value: "frank@elsinga.de"
# configure global
- name: Configure the global git color usage
  community.general.git_config:
    name: color.ui
    scope: file
    file: /root/.gitconfig
    value: auto
- name: Configure the global git username
  community.general.git_config:
    name: user.name
    scope: file
    file: /root/.gitconfig
    value: "Frank Elsinga"
- name: Configure the global git useremail
  community.general.git_config:
    name: user.email
    scope: file
    file: /root/.gitconfig
    value: "frank@elsinga.de"