---
#
# Tasks to be applied to all servers
#

- name: Check connectivity
  ping:
    data: alive
  tags: check
- name: Update apt cache
  apt:
    update_cache: yes
    upgrade: safe
  tags: check

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - tldr
    - tldr
  tags: install

- name: Run settings.yml
  include_tasks: settings.yml
  tags: settings

- name: Run ssh.yml
  include_tasks: ssh.yml
  tags: ssh

- name: Run ufw.yml
  include_tasks: ufw.yml
  tags: ufw

- name: Run fail2ban.yml
  include_tasks: fail2ban.yml
  tags: fail2ban

- name: Run unatended_upgrades.yml
  include_tasks: unatended_upgrades.yml
  tags: unatended_upgrades