---
# ufw setup
- name: Configure http(s) in UFW
  ufw:
    direction: in
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  with_items:
    - { port: 80, proto: any, comment: "HTTP" }
    - { port: 443, proto: any, comment: "HTTPS" }

- name: Configure the api server in UFW
  ufw:
    direction: in
    rule: allow
    port: "{{ item[1] }}"
    proto: "tcp"
    from_ip: "{{ item[0] }}"
    comment: "Kubernetes Controllplane (API+Metrics) from VPN"
  loop: "{{ vpn_ips | product([6443, 10250]) | list }}"

- name: Configure in-cluster etcd 2379 in UFW
  ufw:
    direction: in
    rule: allow
    port: "{{item[1]}}"
    proto: "tcp"
    from_ip: "{{ item[0] }}"
    comment: "k3s HA with embedded etcd from cluster"
  loop: "{{ leaders_ips | product([2379, 2380]) | list }}"

- name: Install k3s
  shell: >
    curl -sfL https://get.k3s.io | sh -s -
    {% if ansible_host == etcd_leader_ip %}--cluster-init{% else %}--server https://{{ etcd_leader_ip }}:6443{% endif %}
    --tls-san {{ loadbalancer_ipv4 }}
    --tls-san {{ loadbalancer_ipv6 }}
    --tls-san controlplane.nav.tum.sexy
  environment:
    K3S_TOKEN: "{{ lookup('ansible.builtin.password', 'credentials/k3s_token length=1024') }}"
    K3S_NODE_NAME: "eliza-{{ 2 + inventory_hostname | replace('tuzeitm-navigatum-', '') | int }}"
    # ipv6 dual stack
    K3S_CLUSTER_CIDR: "{{ cluster_cidr }}"
    K3S_SERVICE_CIDR: "{{ service_cidr }}"

- name: Wait for the k3s service to be running
  wait_for:
    port: 6443
    state: started
    timeout: 300
    delay: 5