---
#
# Tasks to be applied to all k8s instances
#
- name: Wait for the inital etcd database to be created, after which all other nodes can join
  wait_for:
    host: "{{ leader_ip }}"
    port: 6443
    state: started
    timeout: 300
    delay: 5
  when: ansible_host != leader_ip
- name: Install k3s
  shell: curl -sfL https://get.k3s.io | sh - {% if inventory_hostname == 'tuzeitm-navigatum-1' %}--cluster-init{% else %}--server https://{{ leader_ip }}:6443{% endif %}
  environment:
    K3S_NODE_NAME: "eliza-{{ inventory_hostname | replace('tuzeitm-navigatum-1', '') | int | add(2) }}"
    # ipv6 dual stack
    K3S_CLUSTER_CIDR: "{{ cluster_cidr }}"
    K3S_SERVICE_CIDR: "{{ service_cidr }}"

- name: Wait for the k3s service to be running
  wait_for:
    host: "{{ leader_ip }}"
    port: 6443
    state: started
    timeout: 300
    delay: 5

- name: Install helm
  shell: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

- name: Setup the various k3s compontentes
  include_tasks: setup.yml