---
#
# Tasks to be applied to all k8s instances
#

- name: Setup k3s networking
  include_tasks: "k3s_network.yml"

- name: Setup k3s
  include_tasks: "k3s_setup.yml"

- name: Install helm
  shell: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

- name: Setup the various k3s compontentes
  include_tasks: "{{ comp }}"
  loop_control:
    loop_var: comp
  with_fileglob:
    - components/*.yml