---
#
# Tasks to be applied to all k8s instances
#
- name: Wait for the inital etcd database to be created, after which all other nodes can join
  wait_for:
    host: "{{ etcd_leader_ip }}"
    port: 6443
    state: started
    timeout: 300
    delay: 5
  when: ansible_host != etcd_leader_ip

- name: Setup k3s
  include_tasks: "k3s_setup.yml"

- name: Install helm
  shell: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

- name: Setup the various k3s compontentes
  include_tasks: "{{ sys_conf }}"
  loop_control:
    loop_var: sys_conf
  with_fileglob:
    - components/*.yml